### PR TITLE
Handle error when trace file is empty.  Fixes #13

### LINKED ISSUE #13: exception with edbg:file() when trace file is empty
When I haven't started any trace yet, I get:

```
> edbg:file().       
** exception error: bad argument
     in function  binary_to_term/1
        called as binary_to_term(<<>>)
     in call from edbg_tracer:file/2 (src/edbg_tracer.erl, line 356)
```

### PR DESCRIPTION
**Pull request by hshibuya-dd**

### CODE REVIEW

File: src/edbg_tracer.erl [hunk 1]
```diff
@@ -348,13 +348,15 @@ file(Fname, IsElixir) ->
     catch stop_trace(),
     catch edbg_file_tracer:stop(),
     try file:read_file(Fname) of
-        {ok, Tdata} ->
+        {ok, Tdata} when byte_size(Tdata) > 0 ->
```
Comment (etnt) [inline src/edbg_tracer.erl:351]: Perhaps it would be better to use this guard instead:
`when is_binary(Tdata) andalso size(Tdata) > 0`

Comment (etnt) [reply src/edbg_tracer.erl:351]: See also: https://www.erlang.org/doc/man/erlang#size-1

**Review by etnt — APPROVED** [review]
